version: '3.8'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./init-aws.sh:/app/init-aws.sh
    depends_on:
      - localstack
      - aws-init
    restart: on-failure

  localstack:
    image: localstack/localstack:3.2
    container_name: localstack
    ports:
      - "4566:4566"  # Edge port
      - "4571:4571"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_data:/var/lib/localstack"

  aws-init:
    image: amazon/aws-cli
    container_name: aws-init
    depends_on:
      - localstack
    entrypoint: [ "sh", "-c", "chmod +x /app/init-aws.sh && /app/init-aws.sh" ]
    volumes:
      - ./init-aws.sh:/app/init-aws.sh
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566

volumes:
  localstack_data:
