version: '3.8'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:3.2
    container_name: localstack
    ports:
      - "4566:4566"  # Edge port
      - "4571:4571"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_data:/var/lib/localstack"

volumes:
  localstack_data:
