spring:
  cloud:
    aws:
      region:
        static: us-east-1
      accessKey: test
      secretKey: test
      localstack-endpoint: http://localstack:4566
      credentials:
        access-key: test
        secret-key: test
      endpoint:
        sqs: http://localhost:4566
      sqs:
        listener:
          auto-startup: true
